---
- name:  Check if the httpd is installed
  command: "yum list installed httpd " 
  register: output
  failed_when: output.rc == 1 

- block:
  - name: Get HTTPD Configuration file
    get_url:
      url: "{{ https_uri }}"
      dest: /etc/httpd/conf.d/

  - name: Create SSL Directory
    file:
      path: /etc/httpd/conf.d/ssl
      state: directory
      recurse: yes
      mode: 0755
  - name: Create Logs Directory
    file:
      path: /var/www/html/logs
      state: directory
      recurse: yes
      mode: 0755

  - name: Ensure ssl.conf exists
    stat:
      path: /etc/httpd/conf.d/ssl.conf
    register: stat_result
  - name: Rename ssl.conf
    shell: "mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.back"
    when: stat_result.stat.exists

  - name: Retrieve and Extract the SSL Certificate
    unarchive:
      src:  "{{ ssl_uri }}"
      dest: /etc/httpd/conf.d/ssl/
      remote_src: yes
    notify: restart_services

  - name: Create the index.html
    copy: 
      content: " {{ ansible_fqdn }} - ( {{ ansible_default_ipv4.address }} ) - has been customized by Ansible \n "
      dest: /var/www/html/index.html
    when: output.rc == 0
