---
- name: Install required packages
  yum: 
    name: "{{ fw_package }}"
    state: latest
  tags: production

- name: Start and Enable the Fw Services
  service:
    name: "{{ fw_service }}"
    state: started
    enabled: true
  tags: production

- name: Add rules
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
    - http
    - https
  tags: production
