---
- name: Install Required Packages
  yum:
    name: "{{ web_packages }}"
    state: latest

- name: Start Enable "{{ item }}" Service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ web_service }}"


- name: Configuration 
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    mode: 0644
    owner: apache
    group: apache
    setype: httpd_sys_content_t
  notify: Reload Apache
  
