---
- name: TASK12 - Security
  hosts: webservers
  become: yes
  roles:
    - linux-system-roles.selinux
  vars:
    selinux_booleans:
            - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
    
