---
#Task 1 :

- name: Install Web Packages
  yum:
    name:
        - "{{ ansible_local.custom.packages.web_package }}"
        - "{{ ansible_local.custom.packages.db_package }}"
    state: latest


- name: Start, Enable the Web Services
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    state: started 
    enabled: true
- name: Start, Enable the DB Services
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started 
    enabled: true

