---
- hosts: all
  become: yes
  tasks:

  - name: Remove services
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - httpd
      - mariadb
      - php
      - haproxy
      - firewalld
    ignore_errors: yes


  - name: Remove config File
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/www/html/index.html
      - /etc/my.cnf

