---
- name: Implementing Jinja2 Templates
  hosts: webservers
  become: true
  user: automation
  vars:
    system_owner: youssef.lakhlaifi@sfr.com
  tasks:
    
    - name: Templating the motd file
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

